<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css')) ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.min.js')); ?>

    </head>
    <body>
        <div class="container">
            <h1>Введение</h1>
            <p></p>
            <h1>Оглавление</h1>
            <ul>
              <li><a href="<?=$this->url('home'); ?>">Главная</a></li>
              <li><a href="<?=$this->url('task', ['id' => '1']); ?>">Задание 1</a></li>
              <li><a href="<?=$this->url('task', ['id' => '2']); ?>">Задание 2</a></li>
              <li><a href="<?=$this->url('task', ['id' => '3']); ?>">Задание 3</a></li>
              <li><a href="<?=$this->url('task', ['id' => '4']); ?>">Задание 4</a></li>
              <li><a href="<?=$this->url('task', ['id' => '5']); ?>">Задание 5</a></li>
            </ul>
            <h1>Результаты</h1>
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
